### ISSUE TITLE
(Question) Raspberry Pi 2 Compatibility

### ISSUE THREAD

**Issue by djmoore26** [kenschneider18/rpi-metro-display#20]
I have an old Raspberry Pi 2B in my closet collecting dust. Why doesn't your set up work with that model? 

What changes would I have to make to make it compatible?

Thanks!

**Comment by kenschneider18** [comment]
To be honest, I'm not sure it wouldn't. Off the top of my head I don't remember why I said that in the README.

It's definitely compatible with https://github.com/hzeller/rpi-rgb-led-matrix and I'm not really doing any special trickery in the code I wrote.

I'm guessing I said it because the frame rate would likely be bad and you may to run into flickering problems. Even with a 3B I had to tweak the matrix display options to make it livable. https://github.com/kenschneider18/rpi-metro-display/blob/master/rpi-metro-display.py#L103C1-L110C40
